version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:tucson@db:5432/sneaker_db
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tucson
      POSTGRES_DB: sneaker_db
    volumes:
      - sneaker_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # Для автоимпорта дампа при первом запуске

volumes:
  sneaker_data:
